services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: sleep infinity
    nginx:
        image: nginx
        ports:
            - 8080:80